"""
Road Cost Estimator
AI-assisted Maharashtra PWD SSR estimation.

Main features:
- Multiple road-photo upload
- Backend-only AI configuration
- No API-key field for users
- AI photo analysis
- AI-assisted SSR item suggestions
- Automatic quantity calculation from SSR unit
- Manual quantity override
- SSR chapter filtering
- Cost calculation
- CSV download
- Road project chat assistant
"""

import os
import re

import pandas as pd
import streamlit as st

from ai_module import (
    analyze_photos,
    chat_reply,
    get_api_key,
)

from ssr_loader import (
    load_ssr,
    match_chapters,
    search,
)


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Road Cost Estimator",
    page_icon="🛣️",
    layout="wide",
)

st.title("Road Cost Estimator")
st.caption(
    "AI-assisted Maharashtra PWD SSR road estimation"
)


# ============================================================
# SSR CHAPTER GROUPS
# ============================================================

COMMON_NEW = [
    "Road Survey and DPR",
    "Road Surevy",
    "Excavation",
    "Road Sub grade",
    "Road Sub Base and Base Course",
    "Cross Drainage Works",
    "Road Miscellaneous items",
    "Road Furniture",
    "Road Safety",
    "Geosynthetic",
]

CC_EXTRA = [
    "Rigid Pavement",
    "Rigid Pavement (New item)",
    "Expansion Joint",
]

BT_EXTRA = [
    "Road Surfacing Course",
    "Road work",
    "Road works",
    "Road",
]

REPAIR = [
    "Road Maintenance",
    "Bitumen and concrete road Pot Hole Reparing",
    "Road Miscellaneous items",
    "Road Furniture",
    "Road Safety",
    "Cross Drainage Works",
]


# ============================================================
# DEFAULT SSR
# ============================================================

BASE_DIR = os.path.dirname(
    os.path.abspath(__file__)
)

DEFAULT_SSR_FILE = os.path.join(
    BASE_DIR,
    "SSR_2022-23 (2).xlsx",
)


# ============================================================
# SESSION STATE
# ============================================================

DEFAULT_STATE = {
    "ai_results": [],
    "ai": None,
    "photos": [],
    "photo": None,
    "photo_mime": "image/jpeg",
    "selected": {},
    "chat": [],
    "project_id": 0,
}

for key, value in DEFAULT_STATE.items():

    if key not in st.session_state:
        st.session_state[key] = value


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def safe_float(value, default=0.0):

    try:

        number = float(value)

        if pd.isna(number):
            return default

        return number

    except Exception:

        return default


def normalize_unit(unit):

    return (
        str(unit)
        .strip()
        .lower()
        .replace("meter", "metre")
    )


def get_item_kind(row):

    """
    Use the kind generated by ssr_loader.py.

    If it is missing, infer a basic type from the unit.
    """

    kind = str(
        row.get(
            "kind",
            ""
        )
    ).lower().strip()

    if kind:
        return kind

    unit = normalize_unit(
        row.get(
            "unit",
            ""
        )
    )

    if "square metre" in unit:
        return "area"

    if "cubic metre" in unit:
        return "volume"

    if "running metre" in unit:
        return "length"

    if "kilometre" in unit:
        return "km"

    if "number" in unit:
        return "nos"

    if "tonne" in unit:
        return "tonne"

    return "other"


def calculate_quantity(
    row,
    length,
    width,
    thickness,
):
    """
    Calculate a starting quantity from the SSR unit.

    The result is only a calculation based on the
    measurements entered by the user. It is not a
    measurement extracted from the photograph.
    """

    kind = get_item_kind(row)

    length = safe_float(length)
    width = safe_float(width)
    thickness = safe_float(thickness)

    # --------------------------------------------------------
    # Area
    # --------------------------------------------------------

    if kind == "area":

        return max(
            length * width,
            0.0,
        )


    # --------------------------------------------------------
    # Volume
    # --------------------------------------------------------

    if kind == "volume":

        thickness_m = thickness / 1000

        return max(
            length * width * thickness_m,
            0.0,
        )


    # --------------------------------------------------------
    # Length
    # --------------------------------------------------------

    if kind == "length":

        return max(
            length,
            0.0,
        )


    # --------------------------------------------------------
    # Kilometre
    # --------------------------------------------------------

    if kind == "km":

        return max(
            length / 1000,
            0.0,
        )


    # --------------------------------------------------------
    # Other units
    # --------------------------------------------------------

    return 0.0


def ai_recommended_mode():

    analysis = st.session_state.get(
        "ai"
    )

    if not isinstance(
        analysis,
        dict
    ):
        return None

    recommendation = analysis.get(
        "recommended_mode"
    )

    if isinstance(
        recommendation,
        dict
    ):

        value = recommendation.get(
            "value"
        )

        if value in [
            "repair",
            "new_construction",
        ]:

            return value

    return None


def combine_ai_results(results):

    """
    Combine multiple photo results into one master
    analysis without pretending that one photograph
    represents the entire site.

    Recommendations are collected from all photos.
    """

    if not results:
        return None

    valid_results = []

    for entry in results:

        result = entry.get(
            "result"
        )

        if isinstance(
            result,
            dict
        ):

            valid_results.append(
                result
            )

    if not valid_results:
        return None

    # --------------------------------------------------------
    # Mode voting
    # --------------------------------------------------------

    modes = []

    for result in valid_results:

        recommendation = result.get(
            "recommended_mode"
        )

        if isinstance(
            recommendation,
            dict
        ):

            value = recommendation.get(
                "value"
            )

            if value in [
                "repair",
                "new_construction",
            ]:

                modes.append(value)

    master_mode = "unclear"
    master_confidence = "low"

    if modes:

        repair_count = modes.count(
            "repair"
        )

        new_count = modes.count(
            "new_construction"
        )

        if repair_count > new_count:

            master_mode = "repair"

        elif new_count > repair_count:

            master_mode = "new_construction"

        else:

            master_mode = "unclear"

        if len(set(modes)) == 1:

            master_confidence = "medium"

        else:

            master_confidence = "low"


    # --------------------------------------------------------
    # Collect defects
    # --------------------------------------------------------

    defects = []

    for result in valid_results:

        result_defects = result.get(
            "defects",
            []
        )

        if isinstance(
            result_defects,
            list
        ):

            defects.extend(
                result_defects
            )


    # --------------------------------------------------------
    # Collect works
    # --------------------------------------------------------

    works = []

    for result in valid_results:

        result_works = result.get(
            "suggested_works",
            []
        )

        if isinstance(
            result_works,
            list
        ):

            works.extend(
                result_works
            )


    # --------------------------------------------------------
    # Collect parameters
    # --------------------------------------------------------

    parameters = []

    seen_parameters = set()

    for result in valid_results:

        result_parameters = result.get(
            "suggested_parameters",
            []
        )

        if not isinstance(
            result_parameters,
            list
        ):
            continue

        for parameter in result_parameters:

            if not isinstance(
                parameter,
                dict
            ):
                continue

            name = parameter.get(
                "name"
            )

            if not name:
                continue

            if name not in seen_parameters:

                seen_parameters.add(
                    name
                )

                parameters.append(
                    parameter
                )


    # --------------------------------------------------------
    # Site types
    # --------------------------------------------------------

    site_types = []

    for result in valid_results:

        site = result.get(
            "site_type"
        )

        if isinstance(
            site,
            dict
        ):

            value = site.get(
                "value"
            )

            if value:
                site_types.append(value)


    site_type = (
        site_types[0]
        if site_types
        else "unclear"
    )


    # --------------------------------------------------------
    # Return master analysis
    # --------------------------------------------------------

    return {

        "photo_count": len(
            valid_results
        ),

        "recommended_mode": {

            "value": master_mode,

            "confidence": master_confidence,

            "reason": (
                "Combined suggestion from "
                f"{len(valid_results)} photo(s). "
                "Confirm the work type before estimating."
            ),
        },

        "site_type": {

            "value": site_type,

            "confidence": "low",
        },

        "road_type": {

            "value": "unclear",

            "confidence": "low",
        },

        "defects": defects,

        "suggested_works": works,

        "suggested_parameters": parameters,

        "limitations": (
            "Multiple photographs provide supporting "
            "observations only. Actual dimensions and "
            "site measurements must be confirmed by "
            "the engineer."
        ),
    }


def get_ai_keywords():

    """
    Extract useful search keywords from all AI
    suggested works.
    """

    keywords = []

    results = st.session_state.get(
        "ai_results",
        []
    )

    for entry in results:

        result = entry.get(
            "result",
            {}
        )

        if not isinstance(
            result,
            dict
        ):
            continue

        works = result.get(
            "suggested_works",
            []
        )

        if not isinstance(
            works,
            list
        ):
            continue

        for work in works:

            if not isinstance(
                work,
                dict
            ):
                continue

            words = work.get(
                "search_keywords",
                []
            )

            if not isinstance(
                words,
                list
            ):
                continue

            for word in words:

                word = str(
                    word
                ).strip()

                if (
                    word
                    and word.lower()
                    not in [
                        x.lower()
                        for x in keywords
                    ]
                ):

                    keywords.append(
                        word
                    )

    return keywords


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.header(
        "Project Setup"
    )

    st.info(
        "AI assistance is configured in the "
        "application backend."
    )

    st.subheader(
        "SSR Source"
    )

    st.caption(
        "Upload the SSR you want to use for the estimate. "
        "If no SSR is uploaded, the default SSR is used."
    )

    ssr_file = st.file_uploader(

        "Upload SSR",

        type=[
            "xlsx",
            "xls",
            "csv",
            "pdf",
            "docx",
            "txt",
        ],

        help=(
            "Upload the SSR source used by the "
            "estimation engine."
        ),
    )

    if ssr_file is not None:

        st.success(
            f"Using: {ssr_file.name}"
        )

    else:

        st.info(
            "Using default SSR."
        )

        st.caption(
            "SSR_2022-23 (2).xlsx"
        )


# ============================================================
# SSR LOADING
# ============================================================

@st.cache_data(
    show_spinner="Loading SSR..."
)
def get_ssr(
    file_source,
    file_name=None,
):

    return load_ssr(
        file_source
    )


def load_selected_ssr():

    # --------------------------------------------------------
    # Uploaded SSR
    # --------------------------------------------------------

    if ssr_file is not None:

        try:

            return get_ssr(
                ssr_file
            )

        except Exception as error:

            st.error(
                "The uploaded SSR could not be read."
            )

            st.caption(
                "Please check the file format and "
                "SSR structure."
            )

            st.stop()


    # --------------------------------------------------------
    # Default SSR
    # --------------------------------------------------------

    if not os.path.exists(
        DEFAULT_SSR_FILE
    ):

        st.error(
            "Default SSR file was not found."
        )

        st.info(
            "Upload an SSR file from the sidebar."
        )

        st.stop()


    try:

        return get_ssr(
            DEFAULT_SSR_FILE
        )

    except Exception:

        st.error(
            "The default SSR could not be loaded."
        )

        st.stop()


# ============================================================
# SITE PHOTOS
# ============================================================

st.subheader(
    "1. Site Photos"
)

st.caption(
    "Upload one or multiple photos of the road/site."
)


photos = st.file_uploader(

    "Upload Road Photos",

    type=[
        "jpg",
        "jpeg",
        "png",
        "webp",
    ],

    accept_multiple_files=True,

    help=(
        "You can upload multiple photographs "
        "from different views of the same site."
    ),
)


note = st.text_input(

    "Additional Site Information (Optional)",

    placeholder=(
        "Example: Existing road has potholes "
        "and waterlogging."
    ),
)


# ============================================================
# STORE PHOTOS
# ============================================================

if photos:

    current_names = [
        photo.name
        for photo in photos
    ]

    stored_names = [
        photo.get("name")
        for photo in st.session_state.photos
    ]

    if current_names != stored_names:

        st.session_state.photos = []

        for uploaded_photo in photos:

            st.session_state.photos.append(

                {
                    "name": uploaded_photo.name,

                    "bytes": uploaded_photo.getvalue(),

                    "mime": uploaded_photo.type,
                }

            )


        # ----------------------------------------------------
        # First photo retained for chat compatibility
        # ----------------------------------------------------

        if st.session_state.photos:

            first_photo = (
                st.session_state.photos[0]
            )

            st.session_state.photo = (
                first_photo["bytes"]
            )

            st.session_state.photo_mime = (
                first_photo["mime"]
            )


# ============================================================
# DISPLAY PHOTOS
# ============================================================

if photos:

    st.write(
        f"**{len(photos)} photo(s) uploaded.**"
    )

    preview_columns = st.columns(
        min(
            len(photos),
            4
        )
    )

    for index, uploaded_photo in enumerate(
        photos
    ):

        column = preview_columns[
            index % len(preview_columns)
        ]

        with column:

            st.image(
                uploaded_photo,
                caption=uploaded_photo.name,
                use_container_width=True,
            )


    # ========================================================
    # ANALYZE ALL PHOTOS
    # ========================================================

    if st.button(
        "Analyze All Photos",
        type="primary",
        use_container_width=True,
    ):

        # ----------------------------------------------------
        # Clear previous photo analysis
        # ----------------------------------------------------

        st.session_state.ai_results = []

        st.session_state.ai = None

        # Do not automatically destroy manually
        # selected SSR items here. The user may want
        # to continue an existing estimate.


        progress = st.progress(
            0
        )

        status = st.empty()


        # ----------------------------------------------------
        # Backend AI analysis
        # ----------------------------------------------------

        results = analyze_photos(

            st.session_state.photos,

            note=note,

        )


        total = len(
            results
        )


        for index, result in enumerate(
            results
        ):

            status.write(
                f"Processing photo {index + 1} "
                f"of {total}: "
                f"{result['name']}"
            )

            progress.progress(
                (index + 1) / total
            )


        st.session_state.ai_results = (
            results
        )


        # ----------------------------------------------------
        # Combine all photos
        # ----------------------------------------------------

        st.session_state.ai = (
            combine_ai_results(
                results
            )
        )


        status.empty()

        st.success(
            f"Finished processing {total} photo(s)."
        )

        st.rerun()


# ============================================================
# PHOTO ANALYSIS RESULTS
# ============================================================

ai_results = st.session_state.ai_results


if ai_results:

    st.subheader(
        "Photo Analysis Results"
    )


    for index, analysis_entry in enumerate(
        ai_results
    ):

        photo_name = analysis_entry.get(
            "name",
            f"Photo {index + 1}",
        )

        result = analysis_entry.get(
            "result",
            {},
        )


        with st.expander(

            f"Photo {index + 1}: {photo_name}",

            expanded=(
                index == 0
            ),

        ):

            recommendation = result.get(
                "recommended_mode",
                {},
            )


            if isinstance(
                recommendation,
                dict,
            ):

                recommendation_value = (
                    recommendation.get(
                        "value",
                        "unclear",
                    )
                )

                confidence = (
                    recommendation.get(
                        "confidence",
                        "-",
                    )
                )

                reason = (
                    recommendation.get(
                        "reason",
                        "",
                    )
                )

            else:

                recommendation_value = (
                    "unclear"
                )

                confidence = "low"

                reason = ""


            st.info(

                f"**Suggested Work Type:** "
                f"{recommendation_value}  \n"
                f"**Confidence:** {confidence}"

            )


            if reason:

                st.write(
                    f"**Reason:** {reason}"
                )


            # ------------------------------------------------
            # Photo quality
            # ------------------------------------------------

            st.write(
                "**Photo Quality:** "
                + str(
                    result.get(
                        "photo_quality",
                        "-",
                    )
                )
            )


            # ------------------------------------------------
            # Site type
            # ------------------------------------------------

            site_type = result.get(
                "site_type",
                {},
            )

            if isinstance(
                site_type,
                dict,
            ):

                site_type = site_type.get(
                    "value",
                    "-",
                )


            st.write(
                f"**Site Type:** {site_type}"
            )


            # ------------------------------------------------
            # Road type
            # ------------------------------------------------

            road_type = result.get(
                "road_type",
                {},
            )

            if isinstance(
                road_type,
                dict,
            ):

                road_type = road_type.get(
                    "value",
                    "-",
                )


            st.write(
                f"**Road Type:** {road_type}"
            )


            # ------------------------------------------------
            # Surface condition
            # ------------------------------------------------

            st.write(

                "**Surface Condition:** "
                + str(
                    result.get(
                        "surface_condition",
                        "-",
                    )
                )

            )


            # ------------------------------------------------
            # Defects
            # ------------------------------------------------

            defects = result.get(
                "defects",
                [],
            )

            if defects:

                st.markdown(
                    "**Detected / Reported Defects:**"
                )

                st.dataframe(

                    pd.DataFrame(
                        defects
                    ),

                    hide_index=True,

                    use_container_width=True,

                )


            # ------------------------------------------------
            # Suggested works
            # ------------------------------------------------

            suggested_works = result.get(
                "suggested_works",
                [],
            )

            if suggested_works:

                st.markdown(
                    "**Suggested Works:**"
                )

                for work in suggested_works:

                    if not isinstance(
                        work,
                        dict,
                    ):
                        continue

                    st.write(
                        "• "
                        + str(
                            work.get(
                                "work",
                                "-",
                            )
                        )
                    )


            # ------------------------------------------------
            # Parameters
            # ------------------------------------------------

            suggested_parameters = result.get(
                "suggested_parameters",
                [],
            )

            if suggested_parameters:

                st.markdown(
                    "**Measurements / Decisions "
                    "to Confirm:**"
                )

                for parameter in suggested_parameters:

                    if not isinstance(
                        parameter,
                        dict,
                    ):
                        continue

                    name = parameter.get(
                        "name",
                        "-",
                    )

                    why = parameter.get(
                        "why_needed",
                        "",
                    )

                    if why:

                        st.write(
                            f"• **{name}** — {why}"
                        )

                    else:

                        st.write(
                            f"• **{name}**"
                        )


            # ------------------------------------------------
            # Limitations
            # ------------------------------------------------

            limitations = result.get(
                "limitations"
            )

            if limitations:

                st.caption(
                    f"Limitations: {limitations}"
                )


# ============================================================
# TABS
# ============================================================

estimate_tab, chat_tab = st.tabs(
    [
        "Estimate",
        "Chat Assistant",
    ]
)


# ============================================================
# CHAT ASSISTANT
# ============================================================

with chat_tab:

    st.subheader(
        "Road Project Chat Assistant"
    )

    st.caption(
        "Ask questions about your road project "
        "and estimation process."
    )


    # --------------------------------------------------------
    # Chat history
    # --------------------------------------------------------

    for message in st.session_state.chat:

        with st.chat_message(
            message["role"]
        ):

            st.markdown(
                message["content"]
            )


    # --------------------------------------------------------
    # Clear chat
    # --------------------------------------------------------

    if st.button(
        "Clear Chat"
    ):

        st.session_state.chat = []

        st.rerun()


    # --------------------------------------------------------
    # Chat input
    # --------------------------------------------------------

    user_message = st.chat_input(
        "Ask about your road project..."
    )


    if user_message:

        st.session_state.chat.append(

            {
                "role": "user",

                "content": user_message,
            }

        )


        response = chat_reply(

            st.session_state.chat,

            analysis=st.session_state.ai,

            image_bytes=st.session_state.photo,

            mime_type=st.session_state.photo_mime,

        )


        st.session_state.chat.append(

            {
                "role": "assistant",

                "content": response,
            }

        )


        st.rerun()


# ============================================================
# ESTIMATE TAB
# ============================================================

with estimate_tab:

    st.subheader(
        "2. Road Work Selection"
    )


    # --------------------------------------------------------
    # Load SSR
    # --------------------------------------------------------

    df = load_selected_ssr()


    if not isinstance(
        df,
        pd.DataFrame,
    ):

        st.error(
            "SSR loader did not return a DataFrame."
        )

        st.stop()


    # --------------------------------------------------------
    # Required columns
    # --------------------------------------------------------

    required_ssr_columns = [
        "id",
        "item_no",
        "chapter",
        "description",
        "unit",
        "rate",
    ]


    missing_columns = [

        column

        for column in required_ssr_columns

        if column not in df.columns

    ]


    if missing_columns:

        st.error(
            "Required SSR columns are missing."
        )

        st.write(
            missing_columns
        )

        st.stop()


    # --------------------------------------------------------
    # Chapters
    # --------------------------------------------------------

    all_chapters = (

        df["chapter"]

        .dropna()

        .astype(str)

        .unique()

        .tolist()

    )


    # ========================================================
    # WORK MODE
    # ========================================================

    st.subheader(
        "3. Select Work Type"
    )


    modes = [
        "Repair (Existing Road)",
        "New Road Construction",
    ]


    ai_mode = ai_recommended_mode()


    default_mode_index = 0

    if ai_mode == "new_construction":

        default_mode_index = 1


    mode = st.radio(

        "Work Type",

        modes,

        index=default_mode_index,

        horizontal=True,

        help=(
            "AI provides a suggestion only. "
            "Confirm the correct work type."
        ),

    )


    # ========================================================
    # ROAD TYPE
    # ========================================================

    road_kind = None


    if mode == "New Road Construction":

        st.subheader(
            "4. Select Road Type"
        )


        road_kind = st.radio(

            "Road Type",

            [
                "Concrete (CC)",
                "Bitumen / Dambar",
            ],

            horizontal=True,

        )


        if road_kind == "Concrete (CC)":

            wanted_chapters = (
                COMMON_NEW
                + CC_EXTRA
            )

        else:

            wanted_chapters = (
                COMMON_NEW
                + BT_EXTRA
            )

    else:

        wanted_chapters = REPAIR


    # ========================================================
    # PROJECT MEASUREMENTS
    # ========================================================

    st.subheader(
        "5. Project Measurements"
    )

    st.caption(
        "Enter verified site measurements. "
        "The photograph itself is not used as a "
        "measurement source."
    )


    col1, col2, col3, col4 = st.columns(4)


    length = col1.number_input(

        "Length (m)",

        min_value=0.0,

        value=0.0,

        step=1.0,

    )


    width = col2.number_input(

        "Width (m)",

        min_value=0.0,

        value=0.0,

        step=0.1,

    )


    thickness = col3.number_input(

        "Thickness (mm)",

        min_value=0.0,

        value=0.0,

        step=5.0,

    )


    gst = col4.number_input(

        "GST (%)",

        min_value=0.0,

        value=18.0,

        step=1.0,

    )


    # ========================================================
    # CHAPTER FILTER
    # ========================================================

    st.subheader(
        "6. SSR Items"
    )


    preset_chapters = match_chapters(

        all_chapters,

        wanted_chapters,

    )


    # --------------------------------------------------------
    # AI suggested keywords
    # --------------------------------------------------------

    ai_keywords = get_ai_keywords()


    if ai_keywords:

        st.caption(
            "AI suggested SSR search terms: "
            + ", ".join(
                ai_keywords[:10]
            )
        )


    chapters = st.multiselect(

        "SSR Chapters",

        sorted(
            all_chapters
        ),

        default=preset_chapters,

    )


    keywords_text = st.text_input(

        "Search SSR Items",

        placeholder=(
            "Example: excavation, concrete, "
            "bitumen, pothole"
        ),

    )


    keywords = [

        word.strip()

        for word in re.split(
            r",|\n",
            keywords_text
        )

        if word.strip()

    ]


    # --------------------------------------------------------
    # Search SSR
    # --------------------------------------------------------

    try:

        found_items = search(

            df,

            chapters,

            keywords,

        )

    except Exception:

        st.error(
            "SSR search could not be completed."
        )

        st.stop()


    st.caption(
        f"{len(found_items)} SSR item(s) found."
    )


    # ========================================================
    # SSR ITEM PICKER
    # ========================================================

    if found_items.empty:

        st.info(
            "No SSR items found. "
            "Try another chapter or search term."
        )

    else:

        item_view = found_items[
            required_ssr_columns
        ].copy()


        item_view.insert(
            0,
            "Select",
            False,
        )


        edited_items = st.data_editor(

            item_view,

            hide_index=True,

            use_container_width=True,

            height=350,

            disabled=[
                "id",
                "item_no",
                "chapter",
                "description",
                "unit",
                "rate",
            ],

            column_config={

                "Select": st.column_config.CheckboxColumn(
                    "Select"
                ),

                "id": None,

            },

            key="ssr_item_picker",

        )


        # ====================================================
        # ADD SELECTED ITEMS
        # ====================================================

        if st.button(
            "Add Selected Items",
            type="primary",
        ):

            selected_rows = edited_items[
                edited_items["Select"]
            ]


            if selected_rows.empty:

                st.warning(
                    "Please select at least one SSR item."
                )

            else:

                added_count = 0


                for item_id in selected_rows[
                    "id"
                ]:

                    try:

                        item_id = int(
                            item_id
                        )

                    except Exception:

                        continue


                    row = df.loc[
                        item_id
                    ]


                    # ----------------------------------------
                    # Do not overwrite existing quantity
                    # ----------------------------------------

                    if item_id not in (
                        st.session_state.selected
                    ):

                        calculated_quantity = (
                            calculate_quantity(

                                row,

                                length,

                                width,

                                thickness,

                            )
                        )


                        st.session_state.selected[
                            item_id
                        ] = calculated_quantity


                        added_count += 1


                if added_count:

                    st.success(
                        f"{added_count} item(s) added."
                    )

                else:

                    st.info(
                        "Selected items were already "
                        "present in the estimate."
                    )


# ============================================================
# COST ESTIMATE
# ============================================================

    st.subheader(
        "7. Cost Estimate"
    )


    if not st.session_state.selected:

        st.info(
            "No SSR items selected yet."
        )

    else:

        estimate_rows = []


        for item_id, quantity in list(
            st.session_state.selected.items()
        ):

            if item_id not in df.index:

                continue


            row = df.loc[
                item_id
            ]


            estimate_rows.append(

                {

                    "Remove": False,

                    "Item No":
                        row["item_no"],

                    "Description":
                        row["description"],

                    "Unit":
                        row["unit"],

                    "Rate":
                        safe_float(
                            row["rate"]
                        ),

                    "Quantity":
                        safe_float(
                            quantity
                        ),

                }

            )


        if estimate_rows:

            estimate_df = pd.DataFrame(
                estimate_rows
            )


            edited_estimate = st.data_editor(

                estimate_df,

                hide_index=True,

                use_container_width=True,

                disabled=[
                    "Item No",
                    "Description",
                    "Unit",
                    "Rate",
                ],

                column_config={

                    "Remove":
                        st.column_config.CheckboxColumn(
                            "Remove"
                        ),

                    "Quantity":
                        st.column_config.NumberColumn(
                            "Quantity",
                            min_value=0.0,
                            step=0.01,
                            format="%.3f",
                        ),

                    "Rate":
                        st.column_config.NumberColumn(
                            "Rate",
                            format="%.2f",
                        ),

                },

                key="estimate_editor",

            )


            # ------------------------------------------------
            # Update session quantities
            # ------------------------------------------------

            for index, original_row in enumerate(
                estimate_rows
            ):

                item_no = original_row[
                    "Item No"
                ]


                edited_quantity = safe_float(

                    edited_estimate.iloc[
                        index
                    ]["Quantity"]

                )


                for item_id in (
                    st.session_state.selected
                ):

                    stored_row = df.loc[
                        item_id
                    ]


                    if str(
                        stored_row["item_no"]
                    ) == str(
                        item_no
                    ):

                        st.session_state.selected[
                            item_id
                        ] = edited_quantity

                        break


            # ------------------------------------------------
            # Remove rows
            # ------------------------------------------------

            remove_ids = []


            for index, original_row in enumerate(
                estimate_rows
            ):

                if bool(
                    edited_estimate.iloc[
                        index
                    ]["Remove"]
                ):

                    item_no = original_row[
                        "Item No"
                    ]


                    for item_id in (
                        st.session_state.selected
                    ):

                        stored_row = df.loc[
                            item_id
                        ]


                        if str(
                            stored_row["item_no"]
                        ) == str(
                            item_no
                        ):

                            remove_ids.append(
                                item_id
                            )

                            break


            for item_id in remove_ids:

                st.session_state.selected.pop(
                    item_id,
                    None
                )


            # ------------------------------------------------
            # Rebuild final estimate
            # ------------------------------------------------

            final_rows = []


            for item_id, quantity in (
                st.session_state.selected.items()
            ):

                if item_id not in df.index:

                    continue


                row = df.loc[
                    item_id
                ]


                quantity = safe_float(
                    quantity
                )

                rate = safe_float(
                    row["rate"]
                )


                final_rows.append(

                    {

                        "Item No":
                            row["item_no"],

                        "Description":
                            row["description"],

                        "Unit":
                            row["unit"],

                        "Rate":
                            rate,

                        "Quantity":
                            quantity,

                        "Amount":
                            quantity * rate,

                    }

                )


            final_estimate = pd.DataFrame(
                final_rows
            )


            if not final_estimate.empty:

                # --------------------------------------------
                # Totals
                # --------------------------------------------

                subtotal = safe_float(

                    final_estimate[
                        "Amount"
                    ].sum()

                )


                gst_amount = (

                    subtotal
                    * gst
                    / 100

                )


                total = (

                    subtotal
                    + gst_amount

                )


                c1, c2, c3 = st.columns(3)


                c1.metric(

                    "Subtotal",

                    f"Rs {subtotal:,.2f}",

                )


                c2.metric(

                    f"GST ({gst:.0f}%)",

                    f"Rs {gst_amount:,.2f}",

                )


                c3.metric(

                    "Total Estimate",

                    f"Rs {total:,.2f}",

                )


                # --------------------------------------------
                # Download
                # --------------------------------------------

                csv_data = (
                    final_estimate
                    .to_csv(
                        index=False
                    )
                )


                st.download_button(

                    "Download Estimate CSV",

                    csv_data,

                    file_name=(
                        "road_estimate.csv"
                    ),

                    mime="text/csv",

                    use_container_width=True,

                )


        # ----------------------------------------------------
        # Clear estimate
        # ----------------------------------------------------

        if st.button(
            "Clear Selected Items"
        ):

            st.session_state.selected = {}

            st.rerun()


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "Road Cost Estimator | AI-assisted road analysis "
    "and SSR-based estimation"
)
